window.onload = function(){
document.querySelector("#zhujunyan").onclick = function(){ document.querySelector("#zhujunyan_position").scrollIntoView(true); }
document.querySelector("#yangjiaolong").onclick = function(){ document.querySelector("#yangjiaolong_position").scrollIntoView(true); }
document.querySelector("#liuzheng").onclick = function(){ document.querySelector("#liuzheng_position").scrollIntoView(true); }
document.querySelector("#fangqing").onclick = function(){ document.querySelector("#fangqing_position").scrollIntoView(true); }
document.querySelector("#yangyin").onclick = function(){ document.querySelector("#yangyin_position").scrollIntoView(true); }
document.querySelector("#dutao").onclick = function(){ document.querySelector("#dutao_position").scrollIntoView(true); }
document.querySelector("#chenjiong").onclick = function(){ document.querySelector("#chenjiong_position").scrollIntoView(true); }
document.querySelector("#zhaixiaoya").onclick = function(){ document.querySelector("#zhaixiaoya_position").scrollIntoView(true); }
document.querySelector("#zhaoshuang").onclick = function(){ document.querySelector("#zhaoshuang_position").scrollIntoView(true); }
document.querySelector("#sunqilin").onclick = function(){ document.querySelector("#sunqilin_position").scrollIntoView(true); }
document.querySelector("#wanglu").onclick = function(){ document.querySelector("#wanglu_position").scrollIntoView(true); }
document.querySelector("#huoyuchi").onclick = function(){ document.querySelector("#huoyuchi_position").scrollIntoView(true); }
document.querySelector("#yuanyazheng").onclick = function(){ document.querySelector("#huoyuchi_position").scrollIntoView(true); }
document.querySelector("#suhao").onclick = function(){ document.querySelector("#suhao_position").scrollIntoView(true); }
document.querySelector("#cuizhaopeng").onclick = function(){ document.querySelector("#cuizhaopeng_position").scrollIntoView(true); }
document.querySelector("#liaoyiyi").onclick = function(){ document.querySelector("#liaoyiyi_position").scrollIntoView(true); }
document.querySelector("#liulingjie").onclick = function(){ document.querySelector("#liulingjie_position").scrollIntoView(true); }
document.querySelector("#panhao").onclick = function(){ document.querySelector("#panhao_position").scrollIntoView(true); }
document.querySelector("#wuwenming").onclick = function(){ document.querySelector("#wuwenming_position").scrollIntoView(true); }
document.querySelector("#liruihui").onclick = function(){ document.querySelector("#liruihui_position").scrollIntoView(true); }
document.querySelector("#laiyukun").onclick = function(){ document.querySelector("#laiyukun_position").scrollIntoView(true); }
document.querySelector("#zhubo").onclick = function(){ document.querySelector("#zhubo_position").scrollIntoView(true); }
document.querySelector("#yiran").onclick = function(){ document.querySelector("#yiran_position").scrollIntoView(true); }
document.querySelector("#lianzhouhui").onclick = function(){ document.querySelector("#lianzhouhui_position").scrollIntoView(true); }
document.querySelector("#fuxiaoming").onclick = function(){ document.querySelector("#fuxiaoming_position").scrollIntoView(true);  }
document.querySelector("#zhangjuyong").onclick = function(){ window.open("http://staff.ustc.edu.cn/~juyong"); }
document.querySelector("#chenrenjie").onclick = function(){ window.open("http://staff.ustc.edu.cn/~renjiec"); }
document.querySelector("#liuligang").onclick = function(){ window.open("http://staff.ustc.edu.cn/~lgliu"); }

}
